### ISSUE TITLE
Simple configuration for spring boot-hibernate

### ISSUE THREAD

**Issue by danielkauf** [orijtech/sqlcommenter-website#75]
For configuration Hibernate, in case of using spring boot, there is no need to crate a java classs with @Configuration annotation and return a LocalContainerEntityManagerFactoryBean , you can just add
spring.jpa.properties.hibernate.session_factory.statement_inspector=com.google.cloud.sqlcommenter.schibernate.SCHibernate
to the application.properties file.
The suggested solution of creating a LocalContainerEntityManagerFactoryBean, makes that several configurations done in the application.properties file (for example spring.jpa.hibernate.ddl-auto and spring.jpa.show-sql) don't work any more, and is much more cumbersome.

**Comment by odeke-em** [comment]
Please file issues at https://github.com/google/sqlcommenter as there is a
team that is dedicated to maintaining it. This is only the website.
